[package]
name = "ion-hash"
authors = ["Amazon Ion Team <ion-team@amazon.com>"]
description = "Ion Hash"
homepage = "https://github.com/amzn/ion-rust"
repository = "https://github.com/amzn/ion-rust"
license = "Apache-2.0"
readme = "README.md"
keywords = ["ion", "parser", "json", "format", "hash"]
categories = ["encoding", "parser-implementations", "cryptography"]
exclude = [
    "**/.git/**",
    "**/.github/**",
    "**/.travis.yml",
    "**/.appveyor.yml",
    "**/ion-tests/iontestdata/**",
    "*.pdf"
]
version = "0.0.2"
edition = "2018"

[dependencies]
ion-rs = { path = "../", version = "0.5" }
ion-c-sys = { path = "../ion-c-sys", version = "0.4" }
digest = "0.9.0"
sha2 = { version = "0.9.3" }
